CREATE TABLE IF NOT EXISTS rating_mpa (
    rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(16) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT NOT NULL,
    release_date DATE NOT NULL,
    duration     INTEGER NOT NULL,
    rating_mpa   INTEGER REFERENCES rating_mpa(rating_id)
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre    VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id  INTEGER REFERENCES films (film_id),
    genre_id INTEGER REFERENCES genres (genre_id)
);

CREATE TABLE IF NOT EXISTS users(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    VARCHAR(32) NOT NULL,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(64) NOT NULL,
    birthday date
);

CREATE TABLE films_ratings (
    film_id INTEGER REFERENCES films (film_id),
    user_id INTEGER REFERENCES users (user_id)
);

CREATE TABLE friends (
    user_id   INTEGER REFERENCES users (user_id),
    friend_id INTEGER REFERENCES users (user_id),
    status    BOOLEAN NOT NULL
);
